h1 = House.create(name: "Casa Bonita", address: "Malibu av. 34 - 27", description: "Beautiful house with beach view.", city: "Los Angeles", photo: "https://rb.gy/amosv", night_price: 45)
h2 = House.create(name: "Smart House", address: "Chicago av. 34 - 27", description: "Cozy apartment in the center of the city.", city: "Chicago", photo: "https://rb.gy/az7ng", night_price: 30)
h3 = House.create(name: "Wonder Place", address: "Boston av. 34 - 27", description: "Big flat in the cultural neighborhood.", city: "Boston", photo: "https://rb.gy/2o5tw", night_price: 25)
h4 = House.create(name: "Awesome Crib", address: "Medellin av. 34 - 27", description: "Beautiful house with beach view.", city: "Medellin", photo: "https://rb.gy/pieea", night_price: 28)
h5 = House.create(name: "Casa Bolivar", address: "Mexico City av. 34 - 27", description: "House in the middle of the city.", city: "Mexico City", photo: "https://rb.gy/gul6h", night_price: 35)
h6 = House.create(name: "Nice Living", address: "Austin av. 34 - 27", description: "Beautiful house with beach view.", city: "Austin", photo: "https://rb.gy/dzvi3", night_price: 45)
h7 = House.create(name: "Cottage", address: "El Cairo 34 - 27", description: "Cozy apartment in the center of the city.", city: "El Cairo", photo: "https://rb.gy/paine", night_price: 30)
h8 = House.create(name: "Remote Place", address: "Nayrobi av. 34 - 27", description: "Big flat in the cultural neighborhood.", city: "Nayrobi", photo: "https://rb.gy/mcuml", night_price: 25)
h9 = House.create(name: "My House", address: "Bogota av. 34 - 27", description: "Beautiful house with beach view.", city: "Bogota", photo: "https://rb.gy/17pob", night_price: 28)
h10 = House.create(name: "Super House", address: "Santiago av. 34 - 27", description: "House in the middle of the city.", city: "Santiago", photo: "https://rb.gy/9jyd3", night_price: 35)
u1 = User.create(name: "Mohamed Saleh")
u2 = User.create(name: "Bryan Hurtado")
u3 = User.create(name: "Jose Montoya Gomez")
u4 = User.create(name: "Simon Gideon")
Reservation.create(user: u1, house: h1, check_in: "2023-06-09", check_out: "2023-06-14")
Reservation.create(user: u2, house: h1, check_in: "2023-06-20", check_out: "2023-06-25")
Reservation.create(user: u3, house: h1, check_in: "2023-06-27", check_out: "2023-07-03")
Reservation.create(user: u4, house: h5, check_in: "2023-07-19", check_out: "2023-09-23")
